### ISSUE TITLE
error (minor): "No such environment variable"

### ISSUE THREAD

**Issue by albestro** [eth-cscs/slurm-uenv-mount#28] opened 2023-03-03 08:05 UTC
Simply running any command without using any squashes image, everything seems to work fine, but it reports an error message about a missing environment variable.

```
[hohgant][ialberto@nid003192 ~]$ srun hostname
srun: job 41682 queued and waiting for resources
srun: job 41682 has been allocated resources
slurmstepd: error: No such environment variable
nid002536
```

As soon as you load an image, it does not complain anymore

```
[hohgant][ialberto@nid003192 ~]$ srun --uenv-file=/scratch/e1000/bcumming/images/host.squashfs hostname
srun: job 41683 queued and waiting for resources
srun: job 41683 has been allocated resources
nid002077
```

Thanks @bcumming for the support in the quick investigation of it.

**Comment by simonpintarelli** [comment] 2023-03-03 14:03
Hm, I can't reproduce it on my local machine (slurm 22.05.4) and in the docker container (slurm version 20.11.9 as on hohgant).

It uses `spank_getenv` and explicitly treats the case when env variables don't exist here:
https://github.com/eth-cscs/slurm-uenv-mount/blob/tweak-rpm-package/plugin.cpp#L115

According to `/usr/include/slurm/spank.h` on hohgant, `spank_getenv` returns the same error code in case the environment variable isn't found:

```
 *
 *  Returns ESPANK_SUCCESS on success, o/w spank_err_t on failure:
 *    ESPANK_BAD_ARG      = spank handle invalid or len < 0.
 *    ESPANK_ENV_NOEXIST  = environment variable doesn't exist in job's env.
 *    ESPANK_NOSPACE      = buffer too small, truncation occurred.
 *    ESPANK_NOT_REMOTE   = not called in remote context (i.e. from slurmd).
 */
spank_err_t spank_getenv (spank_t spank, const char *var, char *buf, int len);
```

The implementation of `spank_getenv` is here
https://github.com/SchedMD/slurm/blob/master/src/common/spank.c#L2230

it uses https://github.com/SchedMD/slurm/blob/master/src/common/env.c#L269. I suspect it prints an error message, but I can't spot the place in the source code where it comes from at the moment.

**Comment by bcumming** [comment] 2023-03-07 14:49
Maybe the issue is not in the squashfs slurm plugin, but in another plugin?

**Comment by simonpintarelli** [comment] 2023-03-08 17:05
I'm almost sure it is from the squashfs plugin, since the message isn't there if `--uenv-file` is specified, which causes it to skip `spank_getenv`.

**Comment by bcumming** [comment] 2024-02-05 05:43
Closing because this error hasn't been observed in a long time, or by other users

**Closed as completed by bcumming** 2024-02-05 05:43 UTC
